# Generated by Django 3.0.3 on 2020-09-04 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rooms', '0002_auto_20200904_2338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='status',
            field=models.CharField(choices=[('Reserved', 'Reserved'), ('CheckedIn', 'CheckedIn'), ('Free', 'Free')], default='Free', max_length=10),
        ),
    ]
