# Generated by Django 3.0.3 on 2020-09-09 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel', '0015_auto_20200903_1225'),
        ('Rooms', '0005_auto_20200904_2357'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkin',
            name='hotel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Hotel.Hotel'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='hotel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Hotel.Hotel'),
        ),
    ]
