# Generated by Django 3.0.3 on 2020-09-28 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rooms', '0006_auto_20200909_1423'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkin',
            name='is_free',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reservation',
            name='is_free',
            field=models.BooleanField(default=False),
        ),
    ]
