# Generated by Django 3.0.3 on 2020-09-28 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Rooms', '0008_auto_20200928_1150'),
    ]

    operations = [
        # migrations.AlterUniqueTogether(
        #     name='checkin',
        #     unique_together=set(),
        # ),
        # migrations.AlterUniqueTogether(
        #     name='reservation',
        #     unique_together=set(),
        # ),
    ]
