# Generated by Django 3.0.3 on 2020-09-28 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Rooms', '0009_auto_20200928_1211'),
    ]

    operations = [
        # migrations.AlterUniqueTogether(
        #     name='checkin',
        #     unique_together={('room', 'start_date', 'end_date')},
        # ),
        # migrations.AlterUniqueTogether(
        #     name='reservation',
        #     unique_together={('room', 'start_date', 'end_date')},
        # ),
    ]
