# Generated by Django 3.0.3 on 2020-09-28 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel', '0015_auto_20200903_1225'),
        ('Rooms', '0010_auto_20200928_1214'),
    ]

    operations = [
        # migrations.AlterUniqueTogether(
        #     name='checkin',
        #     unique_together={('room', 'guest')},
        # ),
        # migrations.AlterUniqueTogether(
        #     name='reservation',
        #     unique_together={('room', 'guest')},
        # ),
        # migrations.AlterUniqueTogether(
        #     name='room',
        #     unique_together={('room_no', 'hotel')},
        # ),
    ]
