# Generated by Django 3.0.3 on 2020-06-22 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('End_User', '0003_auto_20200622_0425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
