# Generated by Django 3.0.3 on 2020-02-22 12:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('cover_img_location', models.ImageField(upload_to='photos/')),
                ('website', models.CharField(max_length=30)),
                ('API', models.CharField(max_length=30)),
                ('location_lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('location_long', models.DecimalField(decimal_places=6, max_digits=9)),
                ('email', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=13)),
                ('city', models.CharField(max_length=20)),
                ('reg_date', models.DateField(default=django.utils.timezone.now)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('verified', 'verified'), ('unverified', 'unverified'), ('deactivated', 'deactivated')], max_length=30)),
                ('clerk', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SubscriptionofHotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_start_date', models.DateField(default=django.utils.timezone.now)),
                ('sub_end_date', models.DateField()),
                ('sub_detail', models.TextField()),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hotel.Hotel')),
            ],
        ),
        migrations.CreateModel(
            name='HotelGallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_location', models.ImageField(upload_to='HotelImages/')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hotel.Hotel')),
            ],
        ),
        migrations.CreateModel(
            name='HotelFeature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hotel.Feature')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hotel.Hotel')),
            ],
        ),
    ]
