# Generated by Django 3.0.3 on 2020-03-06 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='cover_img_location',
            field=models.ImageField(default='photos/default-logo.png', upload_to='photos/'),
        ),
    ]
