# Generated by Django 3.0.3 on 2020-03-15 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel', '0002_auto_20200306_0923'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='API',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='email',
            field=models.EmailField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='status',
            field=models.CharField(choices=[('verified', 'verified'), ('unverified', 'unverified'), ('deactivated', 'deactivated')], default='unverified', max_length=30),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='website',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
