# Generated by Django 3.0.3 on 2020-03-16 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel', '0003_auto_20200315_0055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='location_lat',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='location_long',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9),
        ),
    ]
