# Generated by Django 3.0.3 on 2020-03-16 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel', '0004_auto_20200316_2155'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='location_desc',
            field=models.TextField(blank=True),
        ),
    ]
