# Generated by Django 3.0.3 on 2020-07-01 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel', '0010_auto_20200630_2240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='status',
            field=models.CharField(choices=[('verified', 'verified'), ('unverified', 'unverified'), ('deactivated', 'deactivated')], default='unverified', max_length=20),
        ),
    ]
