# Generated by Django 3.0.3 on 2020-07-01 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel', '0011_auto_20200701_0834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='website',
            field=models.CharField(max_length=30, null=True, unique=True),
        ),
    ]
